#pragma config(Sensor, port3,  ArmBumper,      sensorVexIQ_Touch)
#pragma config(Sensor, port7,  touchLED,       sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          leftArm,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          sideDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




/**********************************/
/** Movement + Turning Functions **/
/**********************************/

// Turn Right 90 Degrees
void Turn90Right(){
	turnRight(310, degrees, 100);
}

// Turn Left 90 Degrees
void Turn90Left(){
	turnLeft(310, degrees, 100);
}

// Turn 180 Degrees
void Turn180(){
	turnRight(620, degrees, 100);
}

void MoveArm(int EncoderDistance){
	resetMotorEncoder(leftArm);
	resetMotorEncoder(rightArm);
	setMotor(leftArm);
	setMotor(rightArm);
	waitUntil(getMotorEncoder(leftArm) == EncoderDistance);
	stopMultipleMotors(leftArm, rightArm);
}

void lowerArmUntilBumperPressed(){
	// Set Motors to run until bumper pressed
	if(getBumperValue(ArmBumper) == false){
		setMotor(leftArm, -100);
		setMotor(rightArm, -100);
		waitUntil(getBumperValue(ArmBumper) == true);
		stopMultipleMotors(leftArm, rightArm);
	}
}

/**********************/
/** Function Library **/
/**********************/

void init(){
	waitUntil(getTouchLEDValue(touchLED) == true);
}

void PickUpYellowHub(){
	// Re-align with the wall and barrier
	moveMotor(sideDrive, 0.5, seconds, 100);
	backward(1, seconds, 100);
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 980, 100);
	moveMotorTarget(rightArm, 980, 100);
	wait(1, seconds);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, -1.9, rotations, 100);
	// Move forward and pick up yellow hub
	waitUntilMotorMoveComplete(leftArm);
	forward(0.8, rotations, 100);
	moveMotor(clawMotor, 0.5, seconds, -100);
	moveMotorTarget(leftArm, 125, 100);
	moveMotorTarget(rightArm, 125, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up and turn
	backward(0.8, seconds, 100);
	turnLeft(330, degrees, 100);
	// Re-align with wall
	moveMotor(sideDrive, 2, seconds, 100);
}

void move3OrangeHubsTo2x2(){
	// Move forward and turn to face outer wall
	forward(5, rotations, 100);
	// Turn and realign with wall
	moveMotor(sideDrive, 1, seconds, 100);
	moveMotor(sideDrive, -0.2, rotations, 100);
	turnRight(155, degrees, 100);
	// Move sideways to center self with the 3 hubs
	forward(1.8, rotations, 100);
	turnRight(155, degrees, 100);
	// Move forward to push
	forward(3, rotations, 100);
	// Turn left 45 degrees to prepare to push the orange hubs into the scoring zone
	moveMotor(rightDrive, 310, degrees, 100);
	// Push Hubs into the 2x2 scoring
	forward(1, seconds, 20);
	// Put arm down
	moveMotorTarget(leftArm, -800, 100);
	moveMotorTarget(leftArm, -800, 100);
	// Open claw
	moveMotor(clawMotor, 0.5, seconds, -100);
}

//* Main Task *//
task main()
{
	setTouchLEDColor(touchLED, colorViolet);
	waitUntil(getTouchLEDValue(touchLED) == true);
	//lowerArmUntilBumperPressed();
	PickUpYellowHub();
	move3OrangeHubsTo2x2();
}
