#pragma config(Sensor, port2,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  touchLED,       sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          leftArm,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          sideDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/**********************************/
/** Movement + Turning Functions **/
/**********************************/

// Turn Left 90 Degrees
void Turn90Left(){
	turnLeft(320, degrees, 50);
}

void Turn90Right(){
	turnRight(320, degrees, 50);
}

void MoveArm(int EncoderDistance){
	resetMotorEncoder(leftArm);
	resetMotorEncoder(rightArm);
	setMotor(leftArm);
	setMotor(rightArm);
	waitUntil(getMotorEncoder(leftArm) == EncoderDistance);
	stopMultipleMotors(leftArm, rightArm);
}

/**********************/
/** Function Library **/
/**********************/

void PickUpLeftYellowHub(){
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 970, 100);
	moveMotorTarget(rightArm, 970, 100);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, 1.8, rotations, 100);
	// Move forward and pick up yellow hub
	waitUntilMotorMoveComplete(leftArm);
	forward(1, rotations, 100);
	moveMotor(clawMotor, 0.5, seconds, -100);
	moveMotorTarget(leftArm, 225, 100);
	moveMotorTarget(rightArm, 225, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up and turn
	backward(1, seconds, 100);
	Turn90Left();
	// Re-align with wall
	moveMotor(sideDrive, 1, seconds, 100);
}

void PickUpRightYellowHub(){
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 620, 100);
	moveMotorTarget(rightArm, 620, 100);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, 1.8, rotations, -100);
	// Move forward and pick up yellow hub
	waitUntilMotorMoveComplete(leftArm);
	forward(1, rotations, 100);
	moveMotor(clawMotor, 0.5, seconds, -100);
	moveMotorTarget(leftArm, 225, 100);
	moveMotorTarget(rightArm, 225, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up and turn
	backward(1, seconds, 100);
	moveMotorTarget(leftArm, -645, 100);
	moveMotorTarget(rightArm, -645, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Re-align with wall
	forward(0.2, rotations, 50);
	moveMotor(sideDrive, 2, seconds, 100);
	backward(0.5, seconds, 50);

}

void move3OrangeHubsTo2x2(){
	// Move forward, turn, then prepare to push orange hubs
	forward(1, rotations);
	moveMotor(sideDrive, -0.8, rotations, 100);
	moveMotor(leftDrive, 270, degrees, 100);
	// Go forward and group hubs
	forward(1.5, rotations, 100);
	turnRight(175, degrees, 50);
	// Go forward and push hubs against wall
	forward(1.75, rotations, 30);
	moveMotor(rightDrive, 360, degrees, 100);
	// Move forward to score
	forward(1, seconds, 100);
	// Back up and go forward to push hubs agianst the wall
	backward(1, rotations, 100);
	moveMotor(rightDrive, 0.5, rotations, 100);
	if(getGyroDegrees(gyroSensor) < 90){
		setMotor(rightDrive, 20);
		setMotor(leftDrive, -20);
		waitUntil(getGyroDegrees(gyroSensor) == 90);
		stopMultipleMotors(leftDrive, rightDrive);
	}
	backward(2, rotations, 100);
	// Move sideways and align to the wall
	moveMotor(sideDrive, 2, seconds, -100);
	// Push hubs into sccoring zone
	forward(2, rotations, 100);
	moveMotorTarget(leftArm, -845, 100);
	moveMotorTarget(rightArm, -845, 100);
	waitUntilMotorMoveComplete(leftArm);
	moveMotor(clawMotor, 1, seconds, 100);
	backward(1, rotations, 100);
}


void Hang(){
	moveMotor(sideDrive, 0.5, rotations, 100);
	forward(2, rotations, 100);
}

void moveThroughU(){
	// Start from starting position
	moveMotor(sideDrive, 0.5, rotations, -100);
	forward(3, rotations, 100);
	turnLeft(0.3, rotations);
	turnRight(0.3, rotations);
	forward(0.85, rotations, 100);
	wait(0.5, seconds);
	backward(0.6, rotations, 100);
	turnLeft(150, degrees, 100);
	forward(1.55, rotations, 80);
	turnLeft(150, degrees, 100);
	forward(0.3, rotations, 50);
	moveMotor(sideDrive, 1, seconds, -100);
	moveMotor(sideDrive, 0.2, rotations, 100);
	forward(0.3, rotations, 100);
	// Turn with one side and push hubs
	moveMotor(rightDrive, 1.2, rotations, 100);
	wait(0.5, seconds);
	if(getGyroDegrees(gyroSensor) != 180){
		setMotor(rightDrive, 20);
		waitUntil(getGyroDegrees(gyroSensor) == 180);
		stopMotor(rightDrive);
	}
	forward(4, rotations, 50);
	// Move orange hubs to scoring zone
	forward(0.5, seconds, 50);
	turnRight(0.6, rotations, 50);
	backward(0.6, rotations);
	turnRight(0.25, rotations, 50);
	moveMotor(sideDrive, 2, seconds, 100);
	forward(4, rotations, 50);
	Turn90Left();
	// Score the yellow hub
	moveMotorTarget(leftArm, -200, 100);
	moveMotorTarget(rightArm, -200, 100);
	waitUntilMotorMoveComplete(leftArm);
	moveMotor(clawMotor, 0.5, seconds, 100);
}

//* Main Task *//
task main()
{
	wait(1, seconds);
	resetGyro(gyroSensor);
	wait(1, seconds);
	setTouchLEDColor(touchLED, colorViolet);
	waitUntil(getTouchLEDValue(touchLED) == true);
	PickUpLeftYellowHub();
	move3OrangeHubsTo2x2();
	waitUntil(getTouchLEDValue(touchLED) == true);
	PickUpRightYellowHub();
	moveThroughU();
}
