#pragma config(Sensor, port3,  ArmBumper,      sensorVexIQ_Touch)
#pragma config(Sensor, port7,  touchLED,       sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          leftArm,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          sideDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




/**********************************/
/** Movement + Turning Functions **/
/**********************************/

// Turn Right 90 Degrees
void Turn90Right(){
	turnRight(310, degrees, 100);
}

// Turn Left 90 Degrees
void Turn90Left(){
	turnLeft(310, degrees, 100);
}

// Turn 180 Degrees
void Turn180(){
	turnRight(620, degrees, 100);
}

void MoveArm(int EncoderDistance){
	resetMotorEncoder(leftArm);
	resetMotorEncoder(rightArm);
	setMotor(leftArm);
	setMotor(rightArm);
	waitUntil(getMotorEncoder(leftArm) == EncoderDistance);
	stopMultipleMotors(leftArm, rightArm);
}

void lowerArmUntilBumperPressed(){
	// Set Motors to run until bumper pressed
	if(getBumperValue(ArmBumper) == false){
		setMotor(leftArm, -100);
		setMotor(rightArm, -100);
		waitUntil(getBumperValue(ArmBumper) == true);
		stopMultipleMotors(leftArm, rightArm);
	}
}

/**********************/
/** Function Library **/
/**********************/

void init(){
	waitUntil(getTouchLEDValue(touchLED) == true);
}

void PickUpYellowHub(){
	// Re-align with the wall and barrier
	moveMotor(sideDrive, 0.5, seconds, 100);
	backward(1, seconds, 100);
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 980, 100);
	moveMotorTarget(rightArm, 980, 100);
	wait(1, seconds);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, -1.9, rotations, 100);
	// Move forward and pick up yellow hub
	waitUntilMotorMoveComplete(leftArm);
	forward(0.8, rotations, 100);
	moveMotor(clawMotor, 0.5, seconds, -100);
	moveMotorTarget(leftArm, 125, 100);
	moveMotorTarget(rightArm, 125, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up and turn
	backward(0.8, seconds, 100);
	Turn90Left();
	// Re-align with wall
	moveMotor(sideDrive, 2, seconds, 100);
}

//* Main Task *//
task main()
{
	setTouchLEDColor(touchLED, colorViolet);
	waitUntil(getTouchLEDValue(touchLED) == true);
	//lowerArmUntilBumperPressed();
	PickUpYellowHub();
	wait(1, seconds);
}
