#pragma config(Sensor, port2,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port3,  bumperSensor,   sensorVexIQ_Touch)
#pragma config(Sensor, port7,  touchLED,       sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          leftArm,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          hookMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         sideDrive,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************/
/** Function Library **/
/**********************/

void PickUpLeftYellowHub(){
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 1000, 100);
	moveMotorTarget(rightArm, 1000, 100);
	wait(1, seconds);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, 1.7, rotations, 100);
	// Move forward and pick up yellow hub
	backward(0.5, seconds, 100);
	waitUntilMotorMoveComplete(leftArm);
	forward(1, rotations, 100);
	moveMotorTarget(leftArm, 225, 100);
	moveMotorTarget(rightArm, 225, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up and turn
	backward(0.8, seconds, 100);
	turnLeft(330, degrees, 100);
	// Re-align with wall
	moveMotor(sideDrive, 0.6, seconds, 100);
}

void PickUpRightYellowHub(){
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 670, 100);
	moveMotorTarget(rightArm, 670, 100);
	//moveMotorTarget(leftArm, 1030, 100);
	//moveMotorTarget(rightArm, 1030, 100);
	wait(1, seconds);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, 1.8, rotations, -100);
	// Move forward and pick up yellow hub
	backward(0.5, seconds, 100);
	waitUntilMotorMoveComplete(leftArm);
	forward(1.1, rotations, 100);
	moveMotorTarget(leftArm, 225, 100);
	moveMotorTarget(rightArm, 225, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up and turn
	backward(0.5, seconds, 100);
	moveMotorTarget(leftArm, -645, 100);
	moveMotorTarget(rightArm, -645, 100);
	// Re-align with wall
}

void moveThroughU(){
	// Start from starting position
	moveMotorTarget(leftArm, -680, 100);
	moveMotorTarget(rightArm, -680, 100);
	moveMotor(hookMotor, 0.2, rotations);
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, 1.3, rotations, 100);
	forward(3, rotations, 100);
	turnLeft(0.3, rotations);
	turnRight(0.3, rotations);
	forward(0.85, rotations, 100);
	wait(0.5, seconds);
	backward(0.6, rotations, 100);
	turnLeft(150, degrees, 100);
	forward(1.4, rotations, 100);
	turnLeft(150, degrees, 100);
	forward(0.45, rotations, 100);
	moveMotor(sideDrive, 0.5, seconds, -100);
	moveMotor(sideDrive, 0.2, rotations, 100);
	// Turn with one side and push hubs
	moveMotor(rightDrive, 1.3, rotations, 100);
	wait(1, seconds);
	if(getGyroDegrees(gyroSensor) != 190)
		setMotor(rightDrive, 20);
	waitUntil(getGyroDegrees(gyroSensor) == 190);
	stopMotor(rightDrive);
	// Turn with one side and push hubs
	forward(2.7, seconds, 100);
	// Move orange hubs to scoring zone
	turnRight(0.6, rotations, 100);
	backward(0.6, rotations);
	turnRight(0.25, rotations, 100);
	moveMotor(sideDrive, 0.7, seconds, 100);
	forward(2, seconds, 100);
	// Score the yellow hub
	moveMotor(sideDrive, -0.3, rotations, 100);
	turnLeft(0.3, rotations, 100);
	moveMotorTarget(leftArm, -200, 100);
	moveMotorTarget(rightArm, -200, 100);
	waitUntilMotorMoveComplete(leftArm);
	backward(2, rotations, 100);
}

void move3OrangeHubsTo2x2(){
	// Move forward, turn, then prepare to push orange hubs
	forward(1, rotations);
	moveMotor(sideDrive, -0.8, rotations, 100);
	moveMotor(leftDrive, 290, degrees, 100);
	// Go forward and group hubs
	forward(1.7, rotations, 100);
	turnRight(175, degrees, 100);
	// Go forward and push hubs against wall
	forward(1.3, seconds, 100);
	// Back up and go forward to push hubs agianst the wall
	backward(0.5, rotations, 100);
	turnLeft(270, degrees, 100);
	backward(1.8, rotations, 100);
	//backward(1.5, rotations, 100);
	// Move sideways and align to the wall
	moveMotor(sideDrive, 1.5, seconds, -100);
	// Push hubs into sccoring zone
	forward(2, rotations, 100);
	moveMotorTarget(leftArm, -855, 100);
	moveMotorTarget(rightArm, -855, 100);
	waitUntilMotorMoveComplete(leftArm);
	backward(1.1, rotations, 100);
}

void MoveScoringZone(){
	moveMotor(sideDrive, 0.6, rotations, 100);
	moveMotorTarget(leftArm, 925, 100);
	moveMotorTarget(rightArm, 925, 100);
	waitUntilMotorMoveComplete(rightArm);
	forward(2.3, rotations, 100);
	moveMotorTarget(leftArm, -1215, 100);
	moveMotorTarget(rightArm, -1215, 100);
}

void Hook2UHubs(){
	moveMotor(sideDrive, 0.5, rotations, 50);
	forward(2.5, rotations, 100);
	turnRight(0.35, rotations, 50);
	turnLeft(0.35, rotations, 50);
	forward(2, seconds, 100);
	moveMotor(sideDrive, 0.15, rotations, -100);
	stopMotor(hookMotor);
	moveMotor(hookMotor, 0.3, rotations, -20);
	moveMotor(hookMotor, 0.2, rotations, -100);
	setMotor(hookMotor, 0);
	backward(4, rotations, 100);
	moveMotor(sideDrive, 1, rotations, 100)
	turnRight(320, degrees, 50);
	moveMotor(sideDrive, 0.5, rotations, 100);
}

void Pull2HubsInto1x4(){
	backward(3, rotations, 100);
	moveMotor(sideDrive, 0.5, rotations, 100);
	turnRight(320, degrees, 50);
	moveMotor(sideDrive, 0.5, rotations, -100);
	stopMotor(hookMotor);
	forward(1, seconds, 50);
	moveMotor(hookMotor, 0.6, rotations, 50);
	backward(0.5, rotations, 100);
	moveMotorTarget(leftArm, -250, 100);
	moveMotorTarget(rightArm, -250, 100);
	waitUntilMotorMoveComplete(leftArm);
	backward(1, rotations, 100);
}

void HangOnBar(){
	moveMotorTarget(leftArm, 1200, 100);
	moveMotorTarget(rightArm, 1200, 100);
	moveMotor(sideDrive, 0.6, rotations, 100);
	forward(0.5, rotations, 100);
	waitUntilMotorMoveComplete(rightArm);
	forward(1.8, rotations, 100);
	moveMotorTarget(leftArm, -1000, 100);
	moveMotorTarget(rightArm, -1000, 100);
}

void resetArm(){
	setMotor(rightArm, -100);
	setMotor(leftArm, -100);
	waitUntil(getBumperValue(bumperSensor) == true);
	stopMultipleMotors(leftArm, rightArm);
}

void returnToLeftStartZone(){
	turnRight(330, degrees, 100);
	backward(4, rotations, 100);
	turnLeft(330, degrees, 100);
	moveMotor(sideDrive, 1, seconds, -100);
}

//* Main Task *//
task main()
{
	resetGyro(gyroSensor);
	setMotor(hookMotor, 0);
	setTouchLEDColor(touchLED, colorViolet);
	waitUntil(getTouchLEDValue(touchLED) == true);
	PickUpLeftYellowHub();
	move3OrangeHubsTo2x2();
	setTouchLEDColor(touchLED, colorRed);
	waitUntil(getTouchLEDValue(touchLED) == true);
	PickUpRightYellowHub();
	returnToLeftStartZone();
	stopMotor(hookMotor);
	Hook2UHubs();
	Pull2HubsInto1x4();
	while(true){
		resetArm();
		setTouchLEDColor(touchLED, colorBlue);
		waitUntil(getTouchLEDValue(touchLED) == true);
		HangOnBar();
	}

}
